#!/bin/bash

BUCKET=awslambda-reference-architectures
aws s3 cp --acl public-read upload-note.zip s3://deployments-mikedeck/mobile-backend/upload-note.zip
aws s3 cp --acl public-read search.zip s3://deployments-mikedeck/mobile-backend/search.zip
aws s3 cp --acl public-read stream-handler.zip s3://deployments-mikedeck/mobile-backend/stream-handler.zip
