#!/bin/bash

# If running in region other than US EAST 1 and the provided Template
# Then, change BUCKET to your custom bucket name
BUCKET=awslambda-reference-architectures
aws s3 cp --acl public-read upload-note.zip s3://$BUCKET/mobile-backend/upload-note.zip
aws s3 cp --acl public-read search.zip s3://$BUCKET/mobile-backend/search.zip
aws s3 cp --acl public-read stream-handler.zip s3://$BUCKET/mobile-backend/stream-handler.zip
